<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-24T15:30:13 EDT" name="Default suite" finished-at="2024-07-24T15:30:55 EDT" duration-ms="42638">
    <groups>
    </groups>
    <test started-at="2024-07-24T15:30:13 EDT" name="Default test" finished-at="2024-07-24T15:30:55 EDT" duration-ms="42638">
      <class name="valuesite.tests.CentroCostoTestRT">
        <test-method is-config="true" signature="lanzarNavegador()[pri:0, instance:valuesite.tests.CentroCostoTestRT@7d8995e]" started-at="2024-07-24T15:30:13 EDT" name="lanzarNavegador" finished-at="2024-07-24T15:30:19 EDT" duration-ms="6320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanzarNavegador -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:valuesite.tests.CentroCostoTestRT@7d8995e]" started-at="2024-07-24T15:30:19 EDT" name="setUp" finished-at="2024-07-24T15:30:19 EDT" depends-on-methods="valuesite.testcomponents.BaseTest.lanzarNavegador" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="ingresaMantenedor()[pri:0, instance:valuesite.tests.CentroCostoTestRT@7d8995e]" started-at="2024-07-24T15:30:19 EDT" name="ingresaMantenedor" finished-at="2024-07-24T15:30:29 EDT" duration-ms="10442" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ingresaMantenedor -->
        <test-method signature="campoResponsableCcObligatorio()[pri:4, instance:valuesite.tests.CentroCostoTestRT@7d8995e]" started-at="2024-07-24T15:30:29 EDT" name="campoResponsableCcObligatorio" finished-at="2024-07-24T15:30:54 EDT" duration-ms="24649" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[El mensaje de error no se encontró en el tiempo esperado.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: El mensaje de error no se encontró en el tiempo esperado.
at org.junit.Assert.fail(Assert.java:88)
at valuesite.tests.CentroCostoTestRT.campoResponsableCcObligatorio(CentroCostoTestRT.java:122)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- campoResponsableCcObligatorio -->
        <test-method is-config="true" signature="Finalizar()[pri:0, instance:valuesite.tests.CentroCostoTestRT@7d8995e]" started-at="2024-07-24T15:30:54 EDT" name="Finalizar" finished-at="2024-07-24T15:30:55 EDT" duration-ms="1203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Finalizar -->
      </class> <!-- valuesite.tests.CentroCostoTestRT -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
